using System;
using System.Collections.Generic;

namespace pis.data.automation.entities
{
    public partial class EntityAntiVirusForm
    {
        public int EntityCode { get; set; }
        public int CategoryCode { get; set; }
        public int RaitingHits { get; set; }
        public int? Grade { get; set; }
        public bool? IsPreNote { get; set; }
        public bool Locked { get; set; }
        public bool LocalLock { get; set; }
        public int LocalLockUserCode { get; set; }
        public int LocalLockRoleId { get; set; }
        public int LockUserCode { get; set; }
        public int LockRoleId { get; set; }
        public string FieldsStatus { get; set; }
        public bool IsPrivateSearch { get; set; }
        public int PrivateSearchUserCode { get; set; }
        public int PrivateSearchRoleId { get; set; }
        public DateTime? LastSignatureDate { get; set; }
        public string EntityNumber { get; set; }
        public int NumberOfCopies { get; set; }
        public string Version { get; set; }
        public int OriginalVersionCode { get; set; }
        public bool IsSigned { get; set; }
        public int SecurityLevelCode { get; set; }
        public bool? IsConfirm { get; set; }
        public bool? IsActive { get; set; }
        public int FirstEntityCode { get; set; }
        public string From { get; set; }
        public string ImportEntityNumber { get; set; }
        public DateTime? ImportDate { get; set; }
        public string ImportMethod { get; set; }
        public string ImportDesc { get; set; }
        public string ImportOriginNo { get; set; }
        public DateTime? ImportOriginDate { get; set; }
        public string NopgAttached { get; set; }
        public string To { get; set; }
        public string ExportEntityNumber { get; set; }
        public DateTime? ExportDate { get; set; }
        public string ExportMethod { get; set; }
        public string ExportDesc { get; set; }
        public int? ImportIndicatorId { get; set; }
        public int? ExportIndicatorId { get; set; }
        public int? ImportRegisterId { get; set; }
        public int? ImportRegisterRoleId { get; set; }
        public int? ExportRegisterId { get; set; }
        public int? ExportRegisterRoleId { get; set; }
        public string DocType { get; set; }
        public string DocSubject { get; set; }
        public string DocKeywords { get; set; }
        public int? Priority { get; set; }
        public int? ImportPriority { get; set; }
        public int? ExportPriority { get; set; }
        public int CreatorId { get; set; }
        public int CreatorRoleId { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastEditDate { get; set; }
        public string LastUpdateVersion { get; set; }
        public string ThreatName1 { get; set; }
        public string ThreatName2 { get; set; }
        public string ThreatName3 { get; set; }
        public string ThreatName4 { get; set; }
        public string ThreatName5 { get; set; }
        public string ThreatName6 { get; set; }
        public string ThreatName7 { get; set; }
        public string ThreatName9 { get; set; }
        public string ThreatName10 { get; set; }
        public string TargetHost1 { get; set; }
        public string TargetHost2 { get; set; }
        public string TargetHost3 { get; set; }
        public string TargetHost4 { get; set; }
        public string TargetHost5 { get; set; }
        public string TargetHost6 { get; set; }
        public string TargetHost7 { get; set; }
        public string TargetHost8 { get; set; }
        public string TargetHost9 { get; set; }
        public string TargetHost10 { get; set; }
        public string RootCause1 { get; set; }
        public string RootCause2 { get; set; }
        public string RootCause3 { get; set; }
        public string RootCause4 { get; set; }
        public string RootCause5 { get; set; }
        public string RootCause6 { get; set; }
        public string RootCause7 { get; set; }
        public string RootCause8 { get; set; }
        public string RootCause9 { get; set; }
        public string RootCause10 { get; set; }
        public string Total { get; set; }
        public string Threat1 { get; set; }
        public string Threat2 { get; set; }
        public string Threat3 { get; set; }
        public string Threat4 { get; set; }
        public string Threat5 { get; set; }
        public string Threat6 { get; set; }
        public string Threat7 { get; set; }
        public string Threat8 { get; set; }
        public string Threat9 { get; set; }
        public string Threat10 { get; set; }
        public string Target1 { get; set; }
        public string Target2 { get; set; }
        public string Target3 { get; set; }
        public string Target4 { get; set; }
        public string Target5 { get; set; }
        public string Target6 { get; set; }
        public string Target7 { get; set; }
        public string Target8 { get; set; }
        public string Target9 { get; set; }
        public string Target10 { get; set; }
        public string Root1 { get; set; }
        public string Root2 { get; set; }
        public string Root3 { get; set; }
        public string Root4 { get; set; }
        public string Root5 { get; set; }
        public string Root6 { get; set; }
        public string Root7 { get; set; }
        public string Root8 { get; set; }
        public string Root9 { get; set; }
        public string Root10 { get; set; }
        public string Total2 { get; set; }
        public string SystemOutofdate { get; set; }
        public string WithoutAgentNo { get; set; }
        public string Tozihat { get; set; }
        public DateTime? LetterDate { get; set; }
        public string ThreatName8 { get; set; }
        public string LastAgentVersion { get; set; }
        public string LastDlpNum { get; set; }
        public string Events { get; set; }
        public string NoUpdateFile { get; set; }
        public string NoAgentFile { get; set; }
        public string OldAgentFile { get; set; }
        public string OldDlpFile { get; set; }
        public string OldAgentNum { get; set; }
        public string OldDlpNum { get; set; }
    }
}
