using System;
using System.Collections.Generic;

namespace pis.Models
{
    public partial class EntityDarkhastkharid
    {
        public int EntityCode { get; set; }
        public int CategoryCode { get; set; }
        public int RaitingHits { get; set; }
        public int? Grade { get; set; }
        public bool? IsPreNote { get; set; }
        public bool? Locked { get; set; }
        public bool? LocalLock { get; set; }
        public int LocalLockUserCode { get; set; }
        public int LocalLockRoleId { get; set; }
        public int LockUserCode { get; set; }
        public int LockRoleId { get; set; }
        public string FieldsStatus { get; set; }
        public bool? IsPrivateSearch { get; set; }
        public int PrivateSearchUserCode { get; set; }
        public int PrivateSearchRoleId { get; set; }
        public DateTime? LastSignatureDate { get; set; }
        public string EntityNumber { get; set; }
        public int NumberOfCopies { get; set; }
        public string Version { get; set; }
        public int OriginalVersionCode { get; set; }
        public bool? IsSigned { get; set; }
        public int SecurityLevelCode { get; set; }
        public bool? IsConfirm { get; set; }
        public bool? IsActive { get; set; }
        public int FirstEntityCode { get; set; }
        public string From { get; set; }
        public string ImportEntityNumber { get; set; }
        public DateTime? ImportDate { get; set; }
        public string ImportMethod { get; set; }
        public string ImportDesc { get; set; }
        public string ImportOriginNo { get; set; }
        public DateTime? ImportOriginDate { get; set; }
        public string NopgAttached { get; set; }
        public string To { get; set; }
        public string ExportEntityNumber { get; set; }
        public DateTime? ExportDate { get; set; }
        public string ExportMethod { get; set; }
        public string ExportDesc { get; set; }
        public int? ImportIndicatorId { get; set; }
        public int? ExportIndicatorId { get; set; }
        public int? ImportRegisterId { get; set; }
        public int? ImportRegisterRoleId { get; set; }
        public int? ExportRegisterId { get; set; }
        public int? ExportRegisterRoleId { get; set; }
        public string DocType { get; set; }
        public string DocSubject { get; set; }
        public string DocKeywords { get; set; }
        public int? Priority { get; set; }
        public int? ImportPriority { get; set; }
        public int? ExportPriority { get; set; }
        public int CreatorId { get; set; }
        public int CreatorRoleId { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastEditDate { get; set; }
        public string Khradif1 { get; set; }
        public string Khsharh1 { get; set; }
        public string Meghdar1 { get; set; }
        public string Vehedkh1 { get; set; }
        public string Arzesh2 { get; set; }
        public string Sumkh1 { get; set; }
        public string Moredeniaz { get; set; }
        public string Jamkol { get; set; }
        public string Emzadarkhast { get; set; }
        public string Codeetebari1 { get; set; }
        public string Khradif2 { get; set; }
        public string Khradif3 { get; set; }
        public string Khradif4 { get; set; }
        public string Khradif5 { get; set; }
        public string Khradif6 { get; set; }
        public string Khradif7 { get; set; }
        public string Khradif8 { get; set; }
        public string Khradif9 { get; set; }
        public string Khradif10 { get; set; }
        public string Khsharh2 { get; set; }
        public string Khsharh3 { get; set; }
        public string Khsharh4 { get; set; }
        public string Khsharh5 { get; set; }
        public string Khsharh6 { get; set; }
        public string Khsharh7 { get; set; }
        public string Khsharh8 { get; set; }
        public string Khsharh9 { get; set; }
        public string Khsharh10 { get; set; }
        public string Meghdar2 { get; set; }
        public string Meghdar3 { get; set; }
        public string Meghdar4 { get; set; }
        public string Meghdar5 { get; set; }
        public string Meghdar6 { get; set; }
        public string Meghdar7 { get; set; }
        public string Meghdar8 { get; set; }
        public string Meghdar9 { get; set; }
        public string Meghdar10 { get; set; }
        public string Vehedkh2 { get; set; }
        public string Vehedkh3 { get; set; }
        public string Vehedkh4 { get; set; }
        public string Vehedkh5 { get; set; }
        public string Vehedkh6 { get; set; }
        public string Vehedkh7 { get; set; }
        public string Vehedkh8 { get; set; }
        public string Vehedkh9 { get; set; }
        public string Vehedkh10 { get; set; }
        public string Arzesh1 { get; set; }
        public string Arzesh3 { get; set; }
        public string Arzesh4 { get; set; }
        public string Arzesh5 { get; set; }
        public string Arzesh6 { get; set; }
        public string Arzesh7 { get; set; }
        public string Arzesh8 { get; set; }
        public string Arzesh9 { get; set; }
        public string Arzesh10 { get; set; }
        public string Sumkh2 { get; set; }
        public string Sumkh3 { get; set; }
        public string Sumkh4 { get; set; }
        public string Sumkh5 { get; set; }
        public string Sumkh6 { get; set; }
        public string Sumkh7 { get; set; }
        public string Sumkh8 { get; set; }
        public string Sumkh9 { get; set; }
        public string Sumkh10 { get; set; }
        public string Codeetebari2 { get; set; }
        public string Codeetebari3 { get; set; }
        public string Codeetebari4 { get; set; }
        public string Codeetebari5 { get; set; }
        public string Codeetebari6 { get; set; }
        public string Codeetebari7 { get; set; }
        public string Codeetebari8 { get; set; }
        public string Codeetebari9 { get; set; }
        public string Codeetebari10 { get; set; }
        public string Darkhast { get; set; }
        public string Ghesmat { get; set; }
        public string Raisedare { get; set; }
        public string Mavanvahed { get; set; }
        public string Emzamasolghesmat { get; set; }
        public string Emzaraisedare { get; set; }
        public string Emzamavenedare { get; set; }
    }
}
