using System;
using System.Collections.Generic;

namespace pis.Models
{
    public partial class EntityHavaleanbar
    {
        public int EntityCode { get; set; }
        public int CategoryCode { get; set; }
        public int RaitingHits { get; set; }
        public int? Grade { get; set; }
        public bool? IsPreNote { get; set; }
        public bool? Locked { get; set; }
        public bool? LocalLock { get; set; }
        public int LocalLockUserCode { get; set; }
        public int LocalLockRoleId { get; set; }
        public int LockUserCode { get; set; }
        public int LockRoleId { get; set; }
        public string FieldsStatus { get; set; }
        public bool? IsPrivateSearch { get; set; }
        public int PrivateSearchUserCode { get; set; }
        public int PrivateSearchRoleId { get; set; }
        public DateTime? LastSignatureDate { get; set; }
        public string EntityNumber { get; set; }
        public int NumberOfCopies { get; set; }
        public string Version { get; set; }
        public int OriginalVersionCode { get; set; }
        public bool? IsSigned { get; set; }
        public int SecurityLevelCode { get; set; }
        public bool? IsConfirm { get; set; }
        public bool? IsActive { get; set; }
        public int FirstEntityCode { get; set; }
        public string From { get; set; }
        public string ImportEntityNumber { get; set; }
        public DateTime? ImportDate { get; set; }
        public string ImportMethod { get; set; }
        public string ImportDesc { get; set; }
        public string ImportOriginNo { get; set; }
        public DateTime? ImportOriginDate { get; set; }
        public string NopgAttached { get; set; }
        public string To { get; set; }
        public string ExportEntityNumber { get; set; }
        public DateTime? ExportDate { get; set; }
        public string ExportMethod { get; set; }
        public string ExportDesc { get; set; }
        public int? ImportIndicatorId { get; set; }
        public int? ExportIndicatorId { get; set; }
        public int? ImportRegisterId { get; set; }
        public int? ImportRegisterRoleId { get; set; }
        public int? ExportRegisterId { get; set; }
        public int? ExportRegisterRoleId { get; set; }
        public string DocType { get; set; }
        public string DocSubject { get; set; }
        public string DocKeywords { get; set; }
        public int? Priority { get; set; }
        public int? ImportPriority { get; set; }
        public int? ExportPriority { get; set; }
        public int CreatorId { get; set; }
        public int CreatorRoleId { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastEditDate { get; set; }
        public string Radifhav1 { get; set; }
        public string Radifhav2 { get; set; }
        public string Radifhav3 { get; set; }
        public string Radifhav4 { get; set; }
        public string Radifhav5 { get; set; }
        public string Radifhav6 { get; set; }
        public string Radifhav7 { get; set; }
        public string Radifhav8 { get; set; }
        public string Radifhav9 { get; set; }
        public string Radifhav10 { get; set; }
        public string Sharhhav1 { get; set; }
        public string Sharhhav2 { get; set; }
        public string Sharhhav3 { get; set; }
        public string Sharhhav4 { get; set; }
        public string Sharhhav5 { get; set; }
        public string Sharhhav6 { get; set; }
        public string Sharhhav7 { get; set; }
        public string Sharhhav8 { get; set; }
        public string Sharhhav9 { get; set; }
        public string Sharhhav10 { get; set; }
        public string Numfanihav1 { get; set; }
        public string Numfanihav2 { get; set; }
        public string Numfanihav3 { get; set; }
        public string Numfanihav4 { get; set; }
        public string Numfanihav5 { get; set; }
        public string Numfanihav6 { get; set; }
        public string Numfanihav7 { get; set; }
        public string Numfanihav8 { get; set; }
        public string Numfanihav9 { get; set; }
        public string Numfanihav10 { get; set; }
        public string Numcode1 { get; set; }
        public string Numcode2 { get; set; }
        public string Numcode3 { get; set; }
        public string Numcode4 { get; set; }
        public string Numcode5 { get; set; }
        public string Numcode6 { get; set; }
        public string Numcode7 { get; set; }
        public string Numcode8 { get; set; }
        public string Numcode9 { get; set; }
        public string Numcode10 { get; set; }
        public string Meghdarhav1 { get; set; }
        public string Meghdarhav2 { get; set; }
        public string Meghdarhav3 { get; set; }
        public string Meghdarhav4 { get; set; }
        public string Meghdarhav5 { get; set; }
        public string Meghdarhav6 { get; set; }
        public string Meghdarhav7 { get; set; }
        public string Meghdarhav8 { get; set; }
        public string Meghdarhav9 { get; set; }
        public string Meghdarhav10 { get; set; }
        public string Vahedhav1 { get; set; }
        public string Vahedhav2 { get; set; }
        public string Vahedhav3 { get; set; }
        public string Vahedhav4 { get; set; }
        public string Vahedhav5 { get; set; }
        public string Vahedhav6 { get; set; }
        public string Vahedhav7 { get; set; }
        public string Vahedhav8 { get; set; }
        public string Vahedhav9 { get; set; }
        public string Vahedhav10 { get; set; }
        public string Arzeshhav1 { get; set; }
        public string Arzeshhav2 { get; set; }
        public string Arzeshhav3 { get; set; }
        public string Arzeshhav4 { get; set; }
        public string Arzeshhav5 { get; set; }
        public string Arzeshhav6 { get; set; }
        public string Arzeshhav7 { get; set; }
        public string Arzeshhav8 { get; set; }
        public string Arzeshhav9 { get; set; }
        public string Arzeshhav10 { get; set; }
        public string Tedadtahvilhav1 { get; set; }
        public string Tedadtahvilhav2 { get; set; }
        public string Tedadtahvilhav3 { get; set; }
        public string Tedadtahvilhav4 { get; set; }
        public string Tedadtahvilhav5 { get; set; }
        public string Tedadtahvilhav6 { get; set; }
        public string Tedadtahvilhav7 { get; set; }
        public string Tedadtahvilhav8 { get; set; }
        public string Tedadtahvilhav9 { get; set; }
        public string Tedadtahvilhav10 { get; set; }
        public string Moredeniazhav { get; set; }
        public string Emzadarkhasthav { get; set; }
        public string Emzamasolghesmathav { get; set; }
        public string Emzaraisedarehav { get; set; }
        public string Emzamavenedarehav { get; set; }
        public string Darkhasthav { get; set; }
        public string Ghesmathav { get; set; }
        public string Raisedare { get; set; }
        public string Mavanvahedhav { get; set; }
        public string Namedarkhast { get; set; }
        public string Nemaemasol { get; set; }
        public string Namerais { get; set; }
        public string Namemoaven { get; set; }
    }
}
