using System;
using System.Collections.Generic;

namespace pis.Models
{
    public partial class EntityDailyMissionRequest
    {
        public int EntityCode { get; set; }
        public int CategoryCode { get; set; }
        public int RaitingHits { get; set; }
        public int? Grade { get; set; }
        public bool? IsPreNote { get; set; }
        public bool Locked { get; set; }
        public bool LocalLock { get; set; }
        public int LocalLockUserCode { get; set; }
        public int LocalLockRoleId { get; set; }
        public int LockUserCode { get; set; }
        public int LockRoleId { get; set; }
        public string FieldsStatus { get; set; }
        public bool IsPrivateSearch { get; set; }
        public int PrivateSearchUserCode { get; set; }
        public int PrivateSearchRoleId { get; set; }
        public DateTime? LastSignatureDate { get; set; }
        public string EntityNumber { get; set; }
        public int NumberOfCopies { get; set; }
        public string Version { get; set; }
        public int OriginalVersionCode { get; set; }
        public bool IsSigned { get; set; }
        public int SecurityLevelCode { get; set; }
        public bool? IsConfirm { get; set; }
        public bool? IsActive { get; set; }
        public int FirstEntityCode { get; set; }
        public string From { get; set; }
        public string ImportEntityNumber { get; set; }
        public DateTime? ImportDate { get; set; }
        public string ImportMethod { get; set; }
        public string ImportDesc { get; set; }
        public string ImportOriginNo { get; set; }
        public DateTime? ImportOriginDate { get; set; }
        public string NopgAttached { get; set; }
        public string To { get; set; }
        public string ExportEntityNumber { get; set; }
        public DateTime? ExportDate { get; set; }
        public string ExportMethod { get; set; }
        public string ExportDesc { get; set; }
        public int? ImportIndicatorId { get; set; }
        public int? ExportIndicatorId { get; set; }
        public int? ImportRegisterId { get; set; }
        public int? ImportRegisterRoleId { get; set; }
        public int? ExportRegisterId { get; set; }
        public int? ExportRegisterRoleId { get; set; }
        public string DocType { get; set; }
        public string DocSubject { get; set; }
        public string DocKeywords { get; set; }
        public int? Priority { get; set; }
        public int? ImportPriority { get; set; }
        public int? ExportPriority { get; set; }
        public int CreatorId { get; set; }
        public int CreatorRoleId { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastEditDate { get; set; }
        public DateTime? FormDate { get; set; }
        public int? FullName { get; set; }
        public string HeadOfficeName { get; set; }
        public string MissionSubject { get; set; }
        public int? FnameLname1 { get; set; }
        public DateTime? BirthDate1 { get; set; }
        public string FinCode1 { get; set; }
        public int? EmploymentType1 { get; set; }
        public string NationalId1 { get; set; }
        public string RequesterMobileNumber1 { get; set; }
        public int? FnameLname2 { get; set; }
        public DateTime? BirthDate2 { get; set; }
        public string FinCode2 { get; set; }
        public int? EmploymentType2 { get; set; }
        public string NationalId2 { get; set; }
        public string RequesterMobileNumber2 { get; set; }
        public int? FnameLname3 { get; set; }
        public DateTime? BirthDate3 { get; set; }
        public string FinCode3 { get; set; }
        public int? EmploymentType3 { get; set; }
        public string NationalId3 { get; set; }
        public string RequesterMobileNumber3 { get; set; }
        public int? FnameLname4 { get; set; }
        public DateTime? BirthDate4 { get; set; }
        public string FinCode4 { get; set; }
        public int? EmploymentType4 { get; set; }
        public string NationalId4 { get; set; }
        public string RequesterMobileNumber4 { get; set; }
        public int? FnameLname5 { get; set; }
        public DateTime? BirthDate5 { get; set; }
        public string FinCode5 { get; set; }
        public int? EmploymentType5 { get; set; }
        public string NationalId5 { get; set; }
        public string RequesterMobileNumber5 { get; set; }
        public short? Duration { get; set; }
        public int? Source { get; set; }
        public int? Destination { get; set; }
        public int? Route1 { get; set; }
        public int? To1 { get; set; }
        public int? Route2 { get; set; }
        public int? To2 { get; set; }
        public DateTime? FromTheDate { get; set; }
        public DateTime? Untill { get; set; }
        public int? Transport { get; set; }
        public string Route { get; set; }
        public int? MissionLocation { get; set; }
        public int? DeputyName { get; set; }
        public string DeputySign { get; set; }
        public bool? AdministrativeOfficeHeadVerification { get; set; }
        public int? ResponsibleExpertName { get; set; }
        public int? OfficeHeadName { get; set; }
        public int? UnitDeputyName { get; set; }
        public string Pelak { get; set; }
    }
}
